spring.application.name=PruebasSaberPro
server.port=8087
# Cambia esta línea exactamente así:
spring.datasource.url=jdbc:postgresql://db.tysnnghelnfxzmfpnrnv.supabase.co:5432/postgres?sslmode=requirespring.datasource.username=postgres
spring.datasource.password=1097493311a
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.thymeleaf.cache=false
