spring.application.name=PruebasSaberPro
server.port=8087
spring.datasource.url=jdbc:postgresql://localhost:5432/SaberPro
spring.datasource.username=postgres
spring.datasource.password=1097493311
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.thymeleaf.cache=false
